### ISSUE TITLE
Week 3 Review Ticket

### ISSUE THREAD

**Issue by JayManjrekar** [JayManjrekar/jaynewrepository#3]
# Total Score: 4.6/5
CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)
- [ ] CB Create Task Coding requirements documented
- [ ] Runtime of Code(with comments) on Replit/Intellij
Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)
- [ ] Hack#1 Add Phone Number to Sign Up / Authorization screen
- [ ] Hack#2 Add logout to CRUD screen
- [ ] Hack#3 Add login_required to another portion of the project
- [ ] A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.

**Comment by kar722** [comment]
Create Task completed and documented on github pages.
Login/Logout pages attempted showing depth of understanding, but is not completed: -1.4
Extra Credit task completed ==> +1

Total Score: 4.6/5
